name: Example Workflow

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Load environment variables from .env file
        run: |
          set -o allexport
          source .env
          set -o allexport
          # Export each variable to $GITHUB_ENV for the entire job
          while read -r line || [[ -n "$line" ]]; do
            if [[ ! "$line" =~ ^# && "$line" =~ = ]]; then
              echo "$line" >> $GITHUB_ENV
            fi
          done < .env
        shell: bash 


      - name: List environment variables
        run: |
          echo "Listing environment variables:"
          env

      - name: Print specific environment variables
        run: |
          echo "ENV_VAR1 is $ENV_VAR1"
          echo "ENV_VAR2 is $ENV_VAR2"
          echo "registry is $registry"
          echo image_tag="${{ env.Build_NUMBER}}.${{ env.ENV_VAR1}}"
          echo "image tag is $image_tag"
          echo image_num="${{ env.Build_NUMBER}}.${{ env.ENV_VAR2}}-${{ env.registry }}"
          echo "printing image_num is $image_num"

